#!/bin/bash

sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (1,'Bouteille');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (2,'Plastique (PET)');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (3,'Flacon');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (4,'Bidon');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (5,'Conserve');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (6,'Métal');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (7,'Carton');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (8,'Brique');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (9,'Papier');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (10,'Canette');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (11,'Verre');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (12,'Dosette');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (13,'Plastique');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (14,'Sachet');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (15,'Sac');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (16,'Barquette');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (17,'Beutel');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (18,'Emballage');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (19,'Film');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (20,'Pot');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (21,'Tube');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (22,'Filet');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (23,'Bois');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (24,'Gourde');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (25,'Aluminium');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (26,'Polystyrène');"
sqlite3 Treasy_DB "insert  into Matiere (identifiantMat ,nomMat) values (27,'PET opaque');"

sqlite3 Treasy_DB "insert into Poubelle (idPoub ,couleurPoub) values (1, 'Bac bleu');"
sqlite3 Treasy_DB "insert  into Poubelle (idPoub ,couleurPoub) values (2, 'Poubelle grise');"
sqlite3 Treasy_DB "insert  into Poubelle (idPoub ,couleurPoub) values (3, 'Poubelle bleue');"
sqlite3 Treasy_DB "insert  into Poubelle (idPoub ,couleurPoub) values (4, 'Poubelle jaune');"
sqlite3 Treasy_DB "insert  into Poubelle (idPoub ,couleurPoub) values (5, 'Container verre');"
sqlite3 Treasy_DB "insert  into Poubelle (idPoub ,couleurPoub) values (6, 'Point de collecte');"
sqlite3 Treasy_DB "insert  into Poubelle (idPoub ,couleurPoub) values (7, 'Poubelle rouge.');"

sqlite3 Treasy_DB "insert into Region (numeroR ,nomR) values (1,'Occitanie');"

sqlite3 Treasy_DB "insert into Municipalite (idMun ,nomMun,ville,codePostal,idRegion) values (1,'' ,'Saint-Sulpice',81370,1);"
sqlite3 Treasy_DB "insert into Municipalite (idMun ,nomMun,ville,codePostal,idRegion) values (2,'' ,'Toulouse',31000,1);"
sqlite3 Treasy_DB "insert into Municipalite (idMun ,nomMun,ville,codePostal,idRegion) values (3,'' ,'Villeneuve-Tolosane',31270,1);"

sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 1,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 2,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 3,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 4,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 5,'Bien rincer');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 6,'');" 
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 7,' sauf cartons gras');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 8,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 9,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,1, 10,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (5,1, 11,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (6,1, 12,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 13,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 14,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 15,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 16,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 17,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 18,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 19,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 20,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 21,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 22,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 23,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 24,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 25,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 26,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 27,'');"

sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 1,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 2,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 3,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 4,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 5,'Bien rincer');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 6,'');" 
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 7,' sauf cartons gras');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 8,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 9,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (1,2, 10,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (5,2, 11,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (6,2, 12,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 13,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 14,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 15,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 16,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 17,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 18,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 19,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 20,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 21,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 22,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 23,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 24,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 25,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,2, 26,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 27,'');"

sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 1,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 2,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 3,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 4,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 5,'Bien rincer');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 6,'');" 
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 7,' sauf cartons gras');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 8,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 9,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (4,3, 10,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (5,3, 11,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (6,3, 12,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 13,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 14,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 15,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 16,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 17,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 18,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 19,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 20,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 21,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 22,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 23,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 24,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 25,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (7,3, 26,'');"
sqlite3 Treasy_DB "insert into Trie (idPoub, idMun, identifiantMat, consigneTri) values (2,1, 27,'');"

sqlite3 Treasy_DB "insert into Produit (EAN, nomP) values (5000112609516, 'Coca cola zero');" 
sqlite3 Treasy_DB "insert into EstFait (EAN,identifiantMat) values (5000112609516, 2);"


